### ISSUE TITLE
 너무 어렵습니다 ㅠㅠ 

### ISSUE THREAD

**Issue by tjfudrhtop3** [StringBottle/brg-shoe-disp-monit#10]
I needs your help..

**Comment by tjfudrhtop3** [comment]
(),[] 가 뭐입니까

**Comment by tjfudrhtop3** [comment]
Refer to https://hashcode.co.kr/questions/4118/%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%99%80-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC-%ED%95%A0-%EA%B3%B3

**Comment by tjfudrhtop3** [comment]
더 나은 퀄리티의 질문을 위하여.....

1. img = imread(*jpg) 처럼 '~ = ~'라고 일대일(?) 형태로 되어있는것은 이해가 가는데...

  - disp, dest_circles = displacement_measure(dest_img,
                                              src_img,
                                              params = params,
                                              src_circles = src_circles
                                              )
                                              
  - centers, r_estimated, metric = imfindcircles(src_img, 
                                             [min_rad, max_rad],
                                            sensitivity = sensitivity)
                                            
                                            
이 식들 처럼 2대1이나 3대1인 식들은 어떻게 해석을 하는지 궁금합니다.

예를 들면 

x = 3 은 이해가 가는데

x,y,z = 3 이라고 하면

x=y=z=3 인지 아니면 'x,y,z'라는 것이 3이라는 것인지 여쭤보고 싶습니다.


2. 이번주 내내 제일 궁금했던게 첨부된 사진처럼
 매트랩은 데이터의 형식이 어떤 식으로 되어 있는지 바로바로 확인이 가능한데 파이썬 코드는 일일히 print를 해야한다고 배웠습니다.
그것을 어떻게 쥬피터 노트북에서 하는지 궁금합니다.

![Matlab 이미지](https://user-images.githubusercontent.com/83737981/117230775-bb708280-ae58-11eb-8c0d-c69afcc861f1.png)

**Comment by StringBottle** [comment]
1. 해당 내용은 다변수를 반환하는 함수에 대한 내용임 ㅎㅎ 함수가 단순하게 한 개의 값을 출력할 수도 있지만, 여러 개의 값을 출력하는 것도 가능함 

그래서 너가 사용한 비유를 차용하면,

 x, y, z = 3, 5, 10 

그래서 imfindcircle이라는 함수가 반환하는 변수의 갯수가 3개임 

참고자료 
https://dojang.io/mod/page/view.php?id=2340

2. 사실 해당 내용을 가장 정확하게 보여주는 에디터는 Spyder 이긴하고 

jupyter notebook을 이용할 때는 한 개의 셀에 한개의 변수를 입력해서 값을 반환해야함 

아래 링크의 셀 실행 항목 참조 
https://greeksharifa.github.io/references/2019/01/26/Jupyter-usage/

참고 : 추가 셀 생성 위쪽 esc + a, 아래쪽 esc + b 

혹시 중간에 셀을 지웠으면, 아마 에디터 메뉴에서 undo delete cell이라는 메뉴를 찾아야할 거임

**Comment by StringBottle** [comment]
혹시 더 궁금한 사항 있으면 아래 thread로 계속 달지 말고 그냥 새로운 issue open 해줘 ㅎㅎ
