### ISSUE TITLE
제가 최근에 접한 프로그램들에 대하여 질문이 있습니다.

### ISSUE THREAD

**Issue by tjfudrhtop3** [StringBottle/brg-shoe-disp-monit#11]
짧은 기간동안 프로그래밍을 조금 접하면서 예전부터 궁금한 것이 있었습니다.

1. Jupyter Notebook
2. VS
3. Spyder

이 세가지의 차이점은 무엇인가요? 

단순히 표현 방식의 차이 뿐인가요?

**Comment by StringBottle** [comment]
참고자료 
: https://towardsdatascience.com/jupyter-is-taking-a-big-overhaul-in-visual-studio-code-d9dc621e5f11

일단 내 생각에는 2번 3번은 에디터의 성격이 강하고, 즉 코드를 수정하는 과정에 최적화가 되어있고, 

1번은 코드에 조금 확장된 형태의 주석을 달기 위한 목적이 크다고 보면 될 것 같아 ㅎㅎ 

그래서 나는 jupyter notebook을 이용해서 코드를 작성하는 경우도 있긴한데... 다른 사람들이 어떻게 쓰는지는 좀 봐야할 것 같네 ㅎㅎ
