### ISSUE TITLE
utils.py 문의사항 답변 및 추가 질문

### ISSUE THREAD

**Issue by hojunee** [StringBottle/brg-shoe-disp-monit#3]
원래는 Merge를 통해 함께 공유하려했으나, 답변 + 추가 질문사항 남겨드립니다.

### A1
파이썬의 경우 모듈 파일이 잡아먹는 메모리의 양은 상대적으로 극히 작은 편입니다. 또한 어떤 방법을 사용하든 모듈은 sys.modules에 의해 항상 "full import"됩니다.
따라서 이는 전적으로 "사용 스타일"에 기인하여 import 방법을 결정하시면 좋을 것 같습니다.

ex) matplotlib 모듈 내 pyplot을 사용할 것이 알려져있고, 이와 이름을 공유하는 다른 함수가 존재할 가능성이 현격히 적다 
    -> from matplotlib import pyplot 후 pyplot 함수 사용
    matplotlib 모듈 내 여러 모듈을 사용할 것이고, 이와 이름을 공유할 다른 함수가 존재할 가능성이 있다
    -> import matplotlib 후 matplotlib.pyplot 등 사용

### A2
LGTM! (Looks Good To Me - 괜찮아보입니다)

### A3. 
for문과 del을 이용해서 부분부분 나눈 이유는 **메모리 이슈**때문인 것으로 생각됩니다.
del의 경우 사용하지 않는 변수를 메모리에서 해제하여 
아마 밑 부분에서 메모리 복잡도가 커지는 것을 방지하기 위해 다음과 같이 코드를 작성한 것으로 보입니다.
xcStep의 크기에 따라서 이를 한번에 처리해줄 수도 있고, 아니면 밑 코드처럼 나누어서 해야할 수도 있습니다.

### A4. 
방식은 비슷하오나 말씀하신 인덱스 시작이 다르기때문에 반환값이 하나씩 감소한 형태일 것입니다 예를 들어, sub2ind가 3*3에서 (1, 2)를 4로 반환한다면 파이썬은 8을 반환하겠죠. 그런데 이전 코드에서 다뤄진 부분들이 전부 파이썬 기준 인덱싱이 되어있기 때문에 각 숫자가 하나씩 작아진 상태로 인덱싱을 진행하는 것으로 보입니다. - 위 예시라면 (1, 2)가 아닌 (0, 1)이 호출되는 방식 - 인덱스가 0부터 시작한다는 전제하에 코드를 작성한걸로 보여서 문제는 없을 것 같습니다.

**추가 질문 : 여기서 unravel_index의 파라미터로 'C'를 넣으신 이유는 무엇인가요? matlab의 sub2ind는 기본적으로 col-first order를 따르고 이는 Fortran방식이여서 'F'를 써야할 것 같습니다. 🤔**

**Comment by StringBottle** [comment]
사랑합니다 킹호준님!
